### PR TITLE
Implement backend for view facility

### PR DESCRIPTION
**Pull request by ChaiWeiCheng**

### CODE REVIEW

**Review by JTRYI — CHANGES_REQUESTED** [review]
hello wei cheng, i think you can change all the name with location to facility instead, for example, the model class "Location" change to "Facility" instead so that it is more clear.

**Review by Danial-23 — CHANGES_REQUESTED** [review]
Hi Wei Cheng, for the Location class, could you also add a variable to insert images as well?

**Review by JTRYI — APPROVED** [review]
Nice Wei Cheng! All looks good now! You may proceed to merge :)

**Comment by Danial-23** [comment]
Thanks Wei Cheng!! reviewed the changes, you can merge

**Review by Danial-23 — APPROVED** [review]

**Pull request merged**
