### PR TITLE
Implemented backend for booking of facility/add bookings.

### PR DESCRIPTION
**Pull request by JTRYI**
Had manually tested the feature with Postman, was able to add booking to JSON file.

### CODE REVIEW

**Review by Danial-23 — CHANGES_REQUESTED** [review]
If possible, could you make it such that if the timing of the facility is already booked by another user, it shows like a response saying timing is already taken etc. But other than that, all looks good!

**Comment by JTRYI** [comment]
I had implemented the change, please review.

**Review by ChaiWeiCheng — APPROVED** [review]
Looks fine go on

**Review by Danial-23 — APPROVED** [review]
Looks good! Thank you for the change, you can merge now

**Pull request merged**
